image: node:12.14.0

stages:
  - build
  - test
  - deploy

cache:
  paths:
  - node_modules/

build:
  stage: build
  script:
    - echo "Building deploy package"
    - npm install
    - npm run-script build
    - echo "Build successful"
  artifacts:
    expire_in: 1 hour
    paths:
        - build
test:
  stage: test
  script:
    - echo "Running tests"
    - npm run-script test
    - echo "Test successful"
    
# deploy_production:
#   stage: deploy
#   script:
#         - echo "Deploying to server"
#         - npm add gh-pages
#         - npm run-script deploy
#         - echo "Deployed"
